# Generated by Django 5.1.1 on 2024-11-15 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='data',
            field=models.DateField(),
        ),
    ]
